- name: Template kl-client.py
  template:
    src: kl-client.py
    dest: /opt/kl-client.py

- name: Copy bbb_mon.py
  copy:
    src: bbb_mon.py
    dest: /opt/bbb_mon.py

- name: Copy fw_mon.py
  copy:
    src: fw_mon.py
    dest: /opt/fw_mon.py

- name: Save region name
  template:
    src: region
    dest: /etc/region

- name: Install crontab
  copy:
    src: kl_crontab
    dest: /etc/cron.d/kl_crontab

- name: Invoke register
  shell: "/usr/bin/python /opt/kl-client.py register"

- name: Invoke bbb-monitor
  shell: "/usr/bin/python /opt/bbb_mon.py"

- name: Invoke fw-monitor
  shell: "/usr/bin/python /opt/fw_mon.py"
