- import_tasks: apt.yml
  tags:
    - common
    - common_apt

- import_tasks: entropy.yml
  tags:
    - common
    - common_entropy

- import_tasks: prometheus.yml
  tags:
    - common
    - common_prometheus

- import_tasks: firewall.yml
  tags:
    - common
    - common_firewall
