global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
      monitor: 'teleklasa'
rule_files:
  - 'alerts/*.yml'
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - '127.0.0.1:9093'
scrape_configs:
  - job_name: 'ansible'
    scrape_interval: 5s
    scrape_timeout: 5s
    static_configs:
      - targets:
        - 'localhost:9090'
        - 'localhost:9100'
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
{% for item in groups['bbb_hosts'] %}
          - 'https://{{ item }}/bigbluebutton/api/'
          - 'http://{{ item }}/bigbluebutton/api/'
{% endfor %}
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115  # The blackbox exporter's real hostname:port.
  - job_name: 'app'
    scrape_interval: 5s
    scrape_timeout: 5s
    static_configs:
      - targets: ['app.teleklasa.lokalni.pl:9100']
  - job_name: 'bbb'
    static_configs:
      - targets:
{% for item in groups['bbb_hosts'] %}
          - '{{ item }}:9100'
{% endfor %}
