global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
      monitor: 'teleklasa'
rule_files:
  - 'alerts/*.yml'
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - '127.0.0.1:9093'
scrape_configs:
  - job_name: 'ansible'
    scrape_interval: 5s
    scrape_timeout: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'bbb'
    static_configs:
      - targets:
{% for item in groups['bbb_hosts'] %}
          - '{{ item }}:9100'
{% endfor %}
